import {createClient} from '@supabase/supabase-js';
import {products} from '@/lib/products';
import type {ContactDetails} from '@/store/cart';

type DraftOrder = {reference: string; slugs: string[]; contact: ContactDetails; totalCents: number; status: string};
const memory = globalThis as typeof globalThis & {coatOrders?: Map<string, DraftOrder>; stripeEvents?: Set<string>};
memory.coatOrders ??= new Map(); memory.stripeEvents ??= new Set();

function supabaseAdmin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;return url&&key?createClient(url,key,{auth:{persistSession:false}}):null;}
export function createReference(){return `COA-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`}

export async function saveDraft(reference:string,slugs:string[],contact:ContactDetails){const selected=products.filter(p=>slugs.includes(p.slug)&&p.available);const totalCents=selected.reduce((n,p)=>n+p.priceCents,0);const draft={reference,slugs,contact,totalCents,status:'contact_submitted'};const db=supabaseAdmin();if(!db){memory.coatOrders!.set(reference,draft);return draft}const {data:customer,error:customerError}=await db.from('contact_submissions').insert({name:contact.name,email:contact.email,phone:contact.phone,country:contact.country,address:contact.address,city:contact.city,postal_code:contact.postal,preferred_language:contact.language,contact_time:contact.time||null,notes:contact.notes||null,privacy_consented_at:new Date().toISOString()}).select('id').single();if(customerError)throw customerError;const {data:order,error:orderError}=await db.from('orders').insert({reference,status:'contact_submitted',currency:'EUR',amount_cents:totalCents,contact_submission_id:customer.id}).select('id').single();if(orderError)throw orderError;const {error:itemError}=await db.from('order_items').insert(selected.map(p=>({order_id:order.id,product_slug:p.slug,sku:p.sku,title_en:p.localized.en.title,title_zh:p.localized.zh.title,quantity:1,unit_price_cents:p.priceCents})));if(itemError)throw itemError;return draft}

export async function markPaid(reference:string,sessionId:string,eventId:string){if(memory.stripeEvents!.has(eventId))return false;memory.stripeEvents!.add(eventId);const db=supabaseAdmin();if(!db){const order=memory.coatOrders!.get(reference);if(order)order.status='paid';return true}const {error:eventError}=await db.from('payment_events').insert({stripe_event_id:eventId,event_type:'checkout.session.completed',processing_status:'processed'});if(eventError&&eventError.code==='23505')return false;if(eventError)throw eventError;const {error:orderError}=await db.from('orders').update({status:'paid',stripe_session_id:sessionId}).eq('reference',reference);if(orderError)throw orderError;return true}
