'use client';

import {useEffect,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {contactSchema} from '@/lib/schemas';
import type {ContactDetails} from '@/store/cart';
import {useCart} from '@/store/cart';
import {useRouter} from '@/i18n/navigation';

export function CheckoutForm(){const t=useTranslations('Checkout');const locale=useLocale() as 'en'|'zh';const router=useRouter();const checkoutItems=useCart(s=>s.checkoutItems);const existing=useCart(s=>s.contact);const setContact=useCart(s=>s.setContact);const setRef=useCart(s=>s.setOrderReference);const [serverError,setServerError]=useState('');const {register,handleSubmit,reset,formState:{errors,isSubmitting}}=useForm<ContactDetails>({resolver:zodResolver(contactSchema),defaultValues:{language:locale,consent:false}});useEffect(()=>{if(existing)reset(existing)},[existing,reset]);const submit=async(data:ContactDetails)=>{setServerError('');const r=await fetch('/api/orders/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact:data,slugs:checkoutItems})});const payload=await r.json();if(!r.ok){setServerError(payload.error||'Unable to save details');return}setContact(data);setRef(payload.orderReference);router.push('/checkout/review');};return <form className="paper-form checkout-form" onSubmit={handleSubmit(submit)}><div className="form-grid"><Field label={t('name')} error={errors.name?.message}><input {...register('name')} /></Field><Field label={t('email')} error={errors.email?.message}><input type="email" {...register('email')} /></Field><Field label={t('phone')} error={errors.phone?.message}><input {...register('phone')} /></Field><Field label={t('country')} error={errors.country?.message}><input {...register('country')} /></Field></div><Field label={t('address')} error={errors.address?.message}><input {...register('address')} /></Field><div className="form-grid"><Field label={t('city')} error={errors.city?.message}><input {...register('city')} /></Field><Field label={t('postal')} error={errors.postal?.message}><input {...register('postal')} /></Field><Field label={t('language')}><select {...register('language')}><option value="en">English</option><option value="zh">中文</option></select></Field><Field label={t('time')}><input {...register('time')} /></Field></div><Field label={t('notes')}><textarea rows={5} {...register('notes')} /></Field><label className="consent"><input type="checkbox" {...register('consent')}/><span>{t('consent')}</span>{errors.consent&&<small>{t('consentError')}</small>}</label>{serverError&&<p className="form-error" role="alert">{serverError}</p>}<button className="button primary" disabled={isSubmitting}>{t('submit')}</button></form>}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label>{label}{children}{error&&<span className="field-error">{error}</span>}</label>}
